language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp scripts/*.yml before-deploy/
  - cp Dockerfile before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/itamin_CI-CD.zip

deploy:
  - provider: s3
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: itamin-backend-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: itamin-backend-build
    key: itamin_CI-CD.zip
    bundle_type: zip
    application: itamin-backend
    deployment_group: itamin-backend-group
    region: ap-northeast-2

notifications:
  email:
    recipients:
      - rlawjddn5980@naver.com