spring:
  profiles:
    active: prod

---

spring:
  config:
    activate:
      on-profile: dev
  session:
    store-type: jdbc
  datasource:
    url: ENC(VJAdbgW1TLZzMDKOOSqe8/5b0Kf9blSxNY1eh5S2KQM8hrlS2S4Ow21nWIEThYkKlQNidbeHoRGrKyY7Gj3BVt3hBi2FQUm/YJAoB/b+U5T6zA+4sL5shGLCX/ei4YHe)
    username: ENC(fpnzm6OeJF3hBCULOgeh0w==)
    password: ENC(fpnzm6OeJF3hBCULOgeh0w==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
    initialization-mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
  redis:
    host: localhost
    port: 6379
  batch:
    initialize-schema: always

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ENC(FDExiUkjGRvqYXUJRisQE5obxAf5YOHpV/AmapZORaxt9Z7a15oQdZ3sVoOHk1Yf7hbA2WTeUV0dInRL+YdV/1SBFkPipia8S37Nlz0tjMDLJxfib0H7Ew==)
            clientSecret: ENC(BSdvkKGSzhsMqcivOGNKyenoajcesDldhQ20zY3QKdOEN063w4yeDkmYZpqOGbUC)
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
          naver:
            apiURL: "https://openapi.naver.com/v1/nid/me"
            client-id: ENC(pVwoRUttZ9GZaPLTsL36ktnR7pDQJETzuXDo8MPeFIc=)
            client-secret: ENC(2nrUgXZHbiRYiCTY3M+4rjGt71vukcO0)
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

logging:
  level:
    org:
      hibernate.SQL: debug
      hibernate.type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    s3:
      bucket: itamin-backend-images
    credentials:
      instanceProfile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 8080

open:
  api:
    public:
      data:
        servicekey: ENC(uHyS+htHTxPpg2MxEoDEk2m1WaEgkDj7xjPS8AwwDwLcH4dwMU73id2/gCR+wkYmYD1AjXMR2w8NBaVbOoHI/r42vvAKUeqPsbnawo7+zBPBmM/x0vjCWtbLCUIyNku/5FyyH/P9bpQ=)
      publicRentalHouse:
        url: https://data.myhome.go.kr/rentalHouseList

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  header: Authorization
  secret: ENC(AzJYqum03D6EQohX92szB6i2yqhHVr7ToZvRvtt/hYypx2VZCW8M4DD9XwdUKu0D9w8gVsTcZ5TLTcm+FabTtpx1MaoY6x8a0AOnJ4HoPba4kEF/KxWYd2z5WhaKrK37BMkbzY64rjYxvcQcYyiu5nNO6AVDnswOcknAYQm6l7ST+Rqt71IFpmWuW+E5O7/f)
  access-token-validity-in-seconds: 1800000
  refresh-token-validity-in-seconds: 1209600000

---

spring:
  config:
    activate:
      on-profile: prod
  session:
    store-type: jdbc
  datasource:
    url: ENC(VJAdbgW1TLZzMDKOOSqe8/5b0Kf9blSxNY1eh5S2KQM8hrlS2S4Ow21nWIEThYkKlQNidbeHoRGrKyY7Gj3BVt3hBi2FQUm/YJAoB/b+U5T6zA+4sL5shGLCX/ei4YHe)
    username: ENC(fpnzm6OeJF3hBCULOgeh0w==)
    password: ENC(fpnzm6OeJF3hBCULOgeh0w==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
  redis:
    host: redis
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ENC(FDExiUkjGRvqYXUJRisQE5obxAf5YOHpV/AmapZORaxt9Z7a15oQdZ3sVoOHk1Yf7hbA2WTeUV0dInRL+YdV/1SBFkPipia8S37Nlz0tjMDLJxfib0H7Ew==)
            clientSecret: ENC(BSdvkKGSzhsMqcivOGNKyenoajcesDldhQ20zY3QKdOEN063w4yeDkmYZpqOGbUC)
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
          naver:
            apiURL: "https://openapi.naver.com/v1/nid/me"
            client-id: ENC(cvGVif9LzPMgXpYrsxg4qP8kIc4lMFbT4vS5h47sgJQ=)
            client-secret: ENC(dHR9hhj/HdiqJxXQ442LrrONbGAqdWmC)
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

logging:
  level:
    org:
      hibernate.SQL: debug
      hibernate.type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    s3:
      bucket: itamin-backend-images
    credentials:
      instanceProfile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 80

open:
  api:
    public:
      data:
        servicekey: ENC(uHyS+htHTxPpg2MxEoDEk2m1WaEgkDj7xjPS8AwwDwLcH4dwMU73id2/gCR+wkYmYD1AjXMR2w8NBaVbOoHI/r42vvAKUeqPsbnawo7+zBPBmM/x0vjCWtbLCUIyNku/5FyyH/P9bpQ=)
      publicRentalHouse:
        url: https://data.myhome.go.kr/rentalHouseList

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  header: Authorization
  secret: ENC(AzJYqum03D6EQohX92szB6i2yqhHVr7ToZvRvtt/hYypx2VZCW8M4DD9XwdUKu0D9w8gVsTcZ5TLTcm+FabTtpx1MaoY6x8a0AOnJ4HoPba4kEF/KxWYd2z5WhaKrK37BMkbzY64rjYxvcQcYyiu5nNO6AVDnswOcknAYQm6l7ST+Rqt71IFpmWuW+E5O7/f)
  access-token-validity-in-seconds: 1800000
  refresh-token-validity-in-seconds: 1209600000