## ???
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:4400/itamin?characterEncoding=utf8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        #default_batch_fetch_size: 100
#    #open-in-view: false
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page_size: 2000
#        #one-indexed-parameters: true
#
#  profiles:
#    include: oauth
#  session:
#    store-type: jdbc
#
#  redis:
#    host: localhost
#    port: 6379
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace

## ???

spring:
  datasource:
    url: jdbc:mysql://localhost:4400/itamin?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
        #one-indexed-parameters: true

  profiles:
    include: oauth
  session:
    store-type: jdbc

  redis:
    host: redis
    port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace